# Plot frequency spectrum generated by VRT IF data packet write example

# Requires matplotlib and numpy
import matplotlib.pyplot as plt
import numpy as np

sample_rate = 44100

with open("signal.vrt", "rb") as f:
    # Read little endian float32 from file
    s = np.fromfile(f, "<f4")

    # Remove header, stream ID, and trailer
    s = s[2:-1]

    # Transform
    S = np.fft.fft(s)

    # Generate axes
    x = np.linspace(-sample_rate / 2, +sample_rate / 2, len(s))
    y = np.abs(np.fft.fftshift(S))

    # Plot
    plt.plot(x, y)
    plt.title("Frequency spectrum of generated signal")
    plt.xlabel("Frequency [Hz]")
    plt.ylabel("Amplitude")
    plt.show()
