# Plot frequency spectrum generated by VRT IF data packet write example

# Requires matplotlib and numpy
# pip3 install matplotlib numpy
import matplotlib.pyplot as plt
import numpy as np
import sys

sample_rate = 44100

# Parse command line arguments
if len(sys.argv) == 1:
    file_path = "signal.vrt"
if len(sys.argv) == 2:
    file_path = sys.argv[1]
else:
    print(f"Usage: {sys.argv[0]} [file]")
    sys.exit()

with open(file_path, "rb") as f:
    # Read little endian float32 from file
    s = np.fromfile(f, "<f4")

    # Remove header, stream ID, and trailer
    s = s[2:-1]

    # Transform
    S = np.fft.fft(s)

    # Generate axes
    x = np.linspace(-sample_rate / 2, +sample_rate / 2, len(s))
    y = np.abs(np.fft.fftshift(S))

    # Plot
    plt.plot(x, y)
    plt.title("Frequency spectrum of generated signal")
    plt.xlabel("Frequency [Hz]")
    plt.ylabel("Amplitude")
    plt.show()
